'use client';

import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';

interface ApiKeys {
  supabaseUrl: string;
  supabaseAnonKey: string;
  geminiApiKey: string;
  googleMapsApiKey: string;
  googleVisionApiKey: string;
}

interface SetupStep {
  id: string;
  title: string;
  description: string;
  placeholder: string;
  required: boolean;
  validated?: boolean;
}

const AdminSetupWizard: React.FC = () => {
  const [step, setStep] = useState<number>(0);
  const [keys, setKeys] = useState<ApiKeys>({
    supabaseUrl: '',
    supabaseAnonKey: '',
    geminiApiKey: '',
    googleMapsApiKey: '',
    googleVisionApiKey: '',
  });
  const [isActivated, setIsActivated] = useState<boolean>(false);
  const [validationErrors, setValidationErrors] = useState<Record<string, string>>({});
  const [isSaving, setIsSaving] = useState<boolean>(false);

  const steps: SetupStep[] = [
    {
      id: 'supabaseUrl',
      title: 'Supabase Project URL',
      description: 'Your database connection URL from Supabase dashboard',
      placeholder: 'https://your-project.supabase.co',
      required: true,
    },
    {
      id: 'supabaseAnonKey',
      title: 'Supabase Anon Key',
      description: 'Public anonymous key for client-side queries',
      placeholder: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
      required: true,
    },
    {
      id: 'geminiApiKey',
      title: 'Google Gemini API Key',
      description: 'AI concierge (MIA) powered by Gemini 1.5 Flash',
      placeholder: 'AIzaSy...',
      required: true,
    },
    {
      id: 'googleMapsApiKey',
      title: 'Google Maps API Key',
      description: 'For vehicle location mapping and ULEZ routing',
      placeholder: 'AIzaSy...',
      required: true,
    },
    {
      id: 'googleVisionApiKey',
      title: 'Google Vision API Key',
      description: 'Document OCR for instant verification (<30 seconds)',
      placeholder: 'AIzaSy...',
      required: true,
    },
  ];

  useEffect(() => {
    // Load from localStorage on mount
    const savedKeys = localStorage.getItem('mia_api_keys');
    const savedActivation = localStorage.getItem('mia_activated');
    if (savedKeys) {
      setKeys(JSON.parse(savedKeys));
    }
    if (savedActivation === 'true') {
      setIsActivated(true);
    }
  }, []);

  const validateKey = (id: string, value: string): boolean => {
    const errors: Record<string, string> = {};

    switch (id) {
      case 'supabaseUrl':
        if (!value.includes('supabase.co')) {
          errors[id] = 'Invalid Supabase URL. Must contain "supabase.co"';
          return false;
        }
        break;
      case 'supabaseAnonKey':
        if (value.length < 100) {
          errors[id] = 'Key seems too short. Check your Anon Key.';
          return false;
        }
        break;
      case 'geminiApiKey':
      case 'googleMapsApiKey':
      case 'googleVisionApiKey':
        if (!value.startsWith('AIzaSy')) {
          errors[id] = 'Invalid Google API key format (should start with AIzaSy)';
          return false;
        }
        if (value.length < 39) {
          errors[id] = 'Key seems too short.';
          return false;
        }
        break;
    }

    setValidationErrors((prev) => {
      const updated = { ...prev };
      delete updated[id];
      return updated;
    });
    return true;
  };

  const handleKeyChange = (id: string, value: string) => {
    setKeys((prev) => ({ ...prev, [id]: value }));
  };

  const handleNext = async () => {
    const currentStepId = steps[step].id as keyof ApiKeys;
    const currentValue = keys[currentStepId];

    if (!validateKey(currentStepId, currentValue)) {
      return;
    }

    if (step < steps.length - 1) {
      setStep(step + 1);
    }
  };

  const handleActivate = async () => {
    setIsSaving(true);

    // Validate all keys
    let allValid = true;
    for (const stepId of Object.keys(keys)) {
      if (!validateKey(stepId, keys[stepId as keyof ApiKeys])) {
        allValid = false;
      }
    }

    if (!allValid) {
      setIsSaving(false);
      return;
    }

    try {
      // Save to localStorage (in production, this would be encrypted and stored server-side)
      localStorage.setItem('mia_api_keys', JSON.stringify(keys));
      localStorage.setItem('mia_activated', 'true');

      // Create .env.local content (user will need to copy this to their local file)
      const envContent = `
# M&M Auto Performance - API Keys (Generated by Admin Setup Wizard)
NEXT_PUBLIC_SUPABASE_URL=${keys.supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${keys.supabaseAnonKey}
NEXT_PUBLIC_GEMINI_API_KEY=${keys.geminiApiKey}
NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${keys.googleMapsApiKey}
NEXT_PUBLIC_GOOGLE_VISION_API_KEY=${keys.googleVisionApiKey}

# Feature Flags
NEXT_PUBLIC_ENABLE_AI_CONCIERGE=true
NEXT_PUBLIC_ENABLE_TELEMATICS=true
NEXT_PUBLIC_ENABLE_DRIVER_PASSPORT=true

# Environment
NODE_ENV=production
NEXT_PUBLIC_API_URL=https://mandmautoperformance.com
NEXT_PUBLIC_DOMAIN=mandmautoperformance.com
`;

      // Copy to clipboard
      navigator.clipboard.writeText(envContent).catch(() => {
        console.log('Failed to copy. Manual copy needed.');
      });

      setIsActivated(true);
    } catch (error) {
      console.error('Activation failed:', error);
      setValidationErrors({
        general: 'Failed to activate. Check console for errors.',
      });
    }

    setIsSaving(false);
  };

  const handleReset = () => {
    localStorage.removeItem('mia_api_keys');
    localStorage.removeItem('mia_activated');
    setKeys({
      supabaseUrl: '',
      supabaseAnonKey: '',
      geminiApiKey: '',
      googleMapsApiKey: '',
      googleVisionApiKey: '',
    });
    setStep(0);
    setIsActivated(false);
    setValidationErrors({});
  };

  if (isActivated) {
    return (
      <motion.div
        className="rounded-xl bg-gradient-to-br from-electric-turquoise/20 to-baby-blue/20 border border-electric-turquoise/40 p-8 backdrop-blur-md"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <div className="text-center">
          <motion.div
            className="text-5xl mb-4"
            animate={{ scale: [1, 1.1, 1] }}
            transition={{ duration: 2, repeat: Infinity }}
          >
            ✅
          </motion.div>
          <h2 className="text-2xl font-bold text-electric-turquoise mb-2">
            MIA Activated
          </h2>
          <p className="text-gray-300 mb-6">
            Your M&M Auto Performance system is live and ready for deployment.
          </p>

          <div className="space-y-4 mb-6">
            <div className="bg-gunmetal/50 rounded-lg p-4 border border-electric-turquoise/30">
              <p className="text-sm text-gray-400 mb-2">✅ Environment variables configured</p>
              <p className="text-sm text-gray-400 mb-2">✅ Supabase connected</p>
              <p className="text-sm text-gray-400 mb-2">✅ Gemini AI (MIA) ready</p>
              <p className="text-sm text-gray-400 mb-2">✅ Document verification active</p>
              <p className="text-sm text-gray-400">✅ Location services enabled</p>
            </div>

            <div className="bg-dark-gunmetal/50 rounded-lg p-4 border border-baby-blue/20">
              <p className="text-xs text-gray-500 mb-2">📋 Next Steps:</p>
              <ol className="text-sm text-gray-400 space-y-1 text-left">
                <li>1. Copy your .env.local content (already copied to clipboard)</li>
                <li>2. Paste into your local .env.local file</li>
                <li>3. Run: npm install && npm run dev</li>
                <li>4. Test signup, booking, and MIA chat locally</li>
                <li>5. Deploy to Vercel on Monday</li>
              </ol>
            </div>
          </div>

          <div className="flex gap-4">
            <button
              onClick={handleReset}
              className="flex-1 px-4 py-2 bg-gunmetal/50 border border-gray-500 text-gray-300 rounded-lg hover:bg-gunmetal/70 transition"
            >
              Reset Configuration
            </button>
            <a
              href="/admin"
              className="flex-1 px-4 py-2 bg-electric-turquoise text-gunmetal font-semibold rounded-lg hover:bg-electric-turquoise/90 transition text-center"
            >
              Go to Admin Dashboard
            </a>
          </div>
        </div>
      </motion.div>
    );
  }

  const currentStep = steps[step];
  const currentStepId = currentStep.id as keyof ApiKeys;
  const currentValue = keys[currentStepId];
  const hasError = validationErrors[currentStepId];

  return (
    <motion.div
      className="rounded-xl bg-gradient-to-br from-gunmetal to-dark-gunmetal border border-electric-turquoise/30 p-8 backdrop-blur-md"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
    >
      {/* Progress Bar */}
      <div className="mb-8">
        <div className="flex justify-between mb-2">
          <h3 className="text-lg font-semibold text-white">
            Step {step + 1} of {steps.length}: {currentStep.title}
          </h3>
          <span className="text-sm text-gray-400">{Math.round(((step + 1) / steps.length) * 100)}%</span>
        </div>
        <div className="w-full bg-gunmetal/50 rounded-full h-2 overflow-hidden border border-electric-turquoise/20">
          <motion.div
            className="h-full bg-gradient-to-r from-electric-turquoise to-baby-blue"
            initial={{ width: 0 }}
            animate={{ width: `${((step + 1) / steps.length) * 100}%` }}
            transition={{ duration: 0.5 }}
          />
        </div>
      </div>

      {/* Step Description */}
      <div className="mb-6">
        <p className="text-gray-400 text-sm">{currentStep.description}</p>
      </div>

      {/* Input Field */}
      <div className="mb-6">
        <input
          type="password"
          placeholder={currentStep.placeholder}
          value={currentValue}
          onChange={(e) => handleKeyChange(currentStepId, e.target.value)}
          className={`w-full px-4 py-3 rounded-lg bg-dark-gunmetal/80 border ${
            hasError
              ? 'border-red-500/50 focus:border-red-500'
              : 'border-electric-turquoise/30 focus:border-electric-turquoise'
          } text-white placeholder-gray-600 focus:outline-none focus:ring-2 ${
            hasError ? 'focus:ring-red-500/30' : 'focus:ring-electric-turquoise/30'
          } transition`}
          onKeyPress={(e) => e.key === 'Enter' && handleNext()}
        />
        {hasError && <p className="text-red-400 text-sm mt-2">{hasError}</p>}
      </div>

      {/* Navigation Buttons */}
      <div className="flex gap-4">
        <button
          onClick={() => setStep(Math.max(0, step - 1))}
          disabled={step === 0}
          className="flex-1 px-4 py-2 bg-gunmetal/50 border border-gray-500 text-gray-300 rounded-lg hover:bg-gunmetal/70 disabled:opacity-50 disabled:cursor-not-allowed transition"
        >
          ← Previous
        </button>

        {step < steps.length - 1 ? (
          <button
            onClick={handleNext}
            disabled={!currentValue || !!hasError}
            className="flex-1 px-4 py-2 bg-electric-turquoise text-gunmetal font-semibold rounded-lg hover:bg-electric-turquoise/90 disabled:opacity-50 disabled:cursor-not-allowed transition"
          >
            Next →
          </button>
        ) : (
          <button
            onClick={handleActivate}
            disabled={isSaving || !currentValue || !!hasError}
            className="flex-1 px-4 py-2 bg-gradient-to-r from-electric-turquoise to-baby-blue text-gunmetal font-semibold rounded-lg hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed transition"
          >
            {isSaving ? 'Activating...' : '🚀 Activate System'}
          </button>
        )}
      </div>

      {/* Completed Steps Indicator */}
      <div className="mt-6 pt-6 border-t border-electric-turquoise/20">
        <p className="text-xs text-gray-500 mb-3">Setup Progress:</p>
        <div className="flex gap-2">
          {steps.map((s, idx) => (
            <div
              key={s.id}
              className={`h-2 flex-1 rounded-full transition ${
                idx <= step
                  ? 'bg-gradient-to-r from-electric-turquoise to-baby-blue'
                  : 'bg-gunmetal/50 border border-gray-500/30'
              }`}
            />
          ))}
        </div>
      </div>

      {validationErrors.general && (
        <div className="mt-4 p-3 bg-red-500/10 border border-red-500/30 rounded-lg">
          <p className="text-red-400 text-sm">{validationErrors.general}</p>
        </div>
      )}
    </motion.div>
  );
};

export default AdminSetupWizard;
